CXX     = cl.exe
CFLAGS  = -O2 -GA -W3 -DUNICODE -D_UNICODE -nologo
LDFLAGS = /link kernel32.lib user32.lib comctl32.lib shell32.lib gdi32.lib version.lib

out/update-installer.exe: out/main.obj
	$(CXX) $(CFLAGS) -Fe$@ $** $(LDFLAGS)

out/main.obj: main.cpp string.hpp linereader.hpp worker.hpp dynarray.hpp versioninfo.hpp
	$(CXX) $(CFLAGS) -c -Fo$@ main.cpp

