CXX = i686-w64-mingw32-c++
CFLAGS = -std=c++98 -Wall -Wextra -mwindows -municode -DUNICODE -D_UNICODE -fno-exceptions -fno-rtti -gstabs
LDFLAGS = -luser32 -lcomctl32 -lshell32 -lversion -static

out/update-installer.exe: out/main.o
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

out/main.o: main.cpp string.hpp linereader.hpp worker.hpp dynarray.hpp versioninfo.hpp
	$(CXX) $(CFLAGS) -c -o $@ $<

